### ISSUE TITLE
Patch in recent hot fixes from NC-PACE

### ISSUE THREAD

**Issue by cmm-cisco** [becomingahacker/bah-kali-linux-img#6]
Integrate fixes from this cloud-init configuration:

```yaml
bootcmd:
  - systemctl disable blueman-mechanism.service
  - apt install -y locales-all
  - locale-gen --purge en_US.UTF-8
  - dpkg-reconfigure xorg
  - touch /root/.hushlogin

write_files:
  - path: /etc/default/locale
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
```

- [x] Disable blueman (Bluetooth)
- [x] Create a default locale
- [x] Install `locales-all`
- [x] Run `locale-gen`
- [x] Reconfigure `xorg` (may or may not work since this is still running on AWS, but still try)
- [x] `touch /root/.hushlogin` to shut Kali up about running in the cloud
